/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AIInsight = IDL.Record({
  'value' : IDL.Float64,
  'explanation' : IDL.Text,
  'relevanceScore' : IDL.Float64,
  'timeHorizon' : IDL.Text,
  'confidence' : IDL.Float64,
  'signalType' : IDL.Text,
  'impactPotential' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'investmentPreference' : IDL.Text,
});
export const InvestmentPlan = IDL.Record({
  'planId' : IDL.Text,
  'name' : IDL.Text,
  'minimumInvestmentRange' : IDL.Text,
  'description' : IDL.Text,
  'weeklyReturn' : IDL.Float64,
  'riskLevel' : IDL.Text,
  'aiNarrative' : IDL.Text,
});
export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAIInsights' : IDL.Func([], [IDL.Vec(AIInsight)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestmentPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AIInsight = IDL.Record({
    'value' : IDL.Float64,
    'explanation' : IDL.Text,
    'relevanceScore' : IDL.Float64,
    'timeHorizon' : IDL.Text,
    'confidence' : IDL.Float64,
    'signalType' : IDL.Text,
    'impactPotential' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'investmentPreference' : IDL.Text,
  });
  const InvestmentPlan = IDL.Record({
    'planId' : IDL.Text,
    'name' : IDL.Text,
    'minimumInvestmentRange' : IDL.Text,
    'description' : IDL.Text,
    'weeklyReturn' : IDL.Float64,
    'riskLevel' : IDL.Text,
    'aiNarrative' : IDL.Text,
  });
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAIInsights' : IDL.Func([], [IDL.Vec(AIInsight)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestmentPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };