/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIInsight {
  'value' : number,
  'explanation' : string,
  'relevanceScore' : number,
  'timeHorizon' : string,
  'confidence' : number,
  'signalType' : string,
  'impactPotential' : string,
}
export interface DepositEligibility {
  'requiresNumber' : boolean,
  'requiresProfile' : boolean,
  'isEligible' : boolean,
  'requiresAuthentication' : boolean,
  'message' : string,
}
export interface DepositRequest {
  'principal' : Principal,
  'userId' : string,
  'userProfile' : [] | [UserProfile],
  'screenshot' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface InvestmentPlan {
  'planId' : string,
  'name' : string,
  'minimumInvestmentRange' : string,
  'description' : string,
  'weeklyReturn' : number,
  'riskLevel' : string,
  'aiNarrative' : string,
}
export interface Lead { 'name' : string, 'email' : string, 'message' : string }
export interface TelegramBotConfig {
  'active' : boolean,
  'chatId' : string,
  'botToken' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'investmentPreference' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreditSpecificUser' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDepositEligibility' : ActorMethod<[], DepositEligibility>,
  'creditUserWallet' : ActorMethod<[Principal, number], undefined>,
  'getAIInsights' : ActorMethod<[], Array<AIInsight>>,
  'getCallerNumber' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWalletBalance' : ActorMethod<[], [] | [number]>,
  'getCallerWeeklyReturn' : ActorMethod<[], [] | [number]>,
  'getDepositRequestsTest' : ActorMethod<[], Array<DepositRequest>>,
  'getInvestmentPlans' : ActorMethod<[], Array<InvestmentPlan>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getTelegramBotConfig' : ActorMethod<[], TelegramBotConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWalletBalance' : ActorMethod<[Principal], [] | [number]>,
  'getUserWeeklyReturn' : ActorMethod<[Principal], [] | [number]>,
  'initializeCallerWallet' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseInvestmentPlan' : ActorMethod<[string, number], undefined>,
  'registerAuthenticatedUser' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setWalletBalance' : ActorMethod<[Principal, number], undefined>,
  'setWalletBalanceByEmail' : ActorMethod<[string, number], undefined>,
  'submitDeposit' : ActorMethod<[ExternalBlob], string>,
  'submitLead' : ActorMethod<[string, string, string], undefined>,
  'updateTelegramBotConfig' : ActorMethod<[string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];